global:
  # ResolveTimeout is the time after which an alert is declared resolved
  resolve_timeout: 5m

route:
  # The root node of the routing tree.
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  # A list of notification receivers.
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

inhibit_rules:
  # A list of inhibition rules.
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
