version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    hostname: namenode
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - networks1
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    hostname: datanode1
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
      - networks1
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    hostname: datanode2
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
      - networks1
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    hostname: datanode3
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    networks:
      - networks1
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.1.3-java8
    hostname: resourcemanager
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    networks:
      - networks1
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.3-java8
    hostname: historyserver
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    networks:
      - networks1
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188
  
  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.3-java8
    hostname: nodemanager1
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager
    networks:
      - networks1
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8042:8042

  nodemanager2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.3-java8
    hostname: nodemanager2
    container_name: nodemanager2
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager
    networks:
      - networks1
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8142:8042

  nodemanager3:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.3-java8
    hostname: nodemanager3
    container_name: nodemanager3
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager
    networks:
      - networks1
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8242:8042

  zookeeper1:
    image: zookeeper:3.5.6
    hostname: zookeeper1
    container_name: zookeeper1
    restart: always
    networks:
      - networks1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: "server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181"
      #ZOO_STANDALONE_ENABLED: "true"
      #ZOO_ADMINSERVER_ENABLED: "true"
    ports:
      - 2181:2181
      - 8080:8080

  zookeeper2:
    image: zookeeper:3.5.6
    hostname: zookeeper2
    container_name: zookeeper2
    restart: always
    networks:
      - networks1
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: "server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181"
      #ZOO_STANDALONE_ENABLED: "true"
      #ZOO_ADMINSERVER_ENABLED: "true"
    ports:
      - 2182:2181
      - 8081:8080

  zookeeper3:
    image: zookeeper:3.5.6
    hostname: zookeeper3
    container_name: zookeeper3
    restart: always
    networks:
      - networks1
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: "server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181"
      #ZOO_STANDALONE_ENABLED: "true"
      #ZOO_ADMINSERVER_ENABLED: "true"
    ports:
      - 2183:2181
      - 8082:8080

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:

networks:
  networks1:
    external:
      name: appnet

# URL Paths for Hadoop Services
# Namenode: http://<dockerhadoop_IP_address>:9870/dfshealth.html#tab-overview
# History Server: http://<dockerhadoop_IP_address>:8188/applicationhistory
# Datanode: http://<dockerhadoop_IP_address>:9864/
# Nodemanager: http://<dockerhadoop_IP_address>:8042/node
# Resource Manager: http://<dockerhadoop_IP_address>:8088/
# Zookeeper Admin: http://<dockerhadoop_IP_address>:8080/commands
