# [[[Deploying Elasticsearch on Kubernetes]]]
# Elasticsearch node discovery through Headless Service & Elasticsearch cluster using StatefulSet
# https://blog.knoldus.com/deploying-elasticsearch-on-kubernetes/
# https://dzone.com/articles/running-elasticsearch-on-kubernetes
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# https://www.elastic.co/elastic-cloud-kubernetes
#
# We have used multiple initContainers to setup our node before running the Elasticsearch image. Let us look into them one-by-one:
# - fix-the-volume-permission: This is to fix the volume permission because by default Elasticsearch container is not run as non root user.
# - increase-the-vm-max-map-count: This is used to increace the default vm.max_map_count to 262144
# - increase-the-ulimit: Used for increasing the ulimit
#
# <cmd> kubectl apply -f elasticsearch-deploy.yaml
# <cmd> kubectl port-forward -n myspace statefulset/elasticsearch 9200:9200
# <cmd> kubectl exec -i -t deploy/busybox -- nslookup es-headless
#       Server:    10.96.0.10
#       Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local
#       Name:      es-headless
#       Address 1: 10.244.3.7 elasticsearch-2.es-headless.myspace.svc.cluster.local
#       Address 2: 10.244.3.5 elasticsearch-0.es-headless.myspace.svc.cluster.local
#       Address 3: 10.244.1.6 elasticsearch-1.es-headless.myspace.svc.cluster.local
#
# <cmd> for i in 0 1 2; do kubectl exec elasticsearch-$i -- hostname -f; done
# <cmd> for i in 0 1 2; do kubectl get pod elasticsearch-$i --template {{.spec.nodeName}}; echo ""; done
#
# elasticsearch-storage.yaml
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage
# provisioner: rancher.io/local-path
# volumeBindingMode: WaitForFirstConsumer
# ---
# elasticsearch-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: es-headless
  namespace: myspace
  labels:
    service: es-headless
spec:
  clusterIP: None # Setting the clusterIP field in a service spec to 'None' makes the service headless.
  ports:
  - name: client
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: local
    port: 9300
    targetPort: 9300
    protocol: TCP
  selector:
    service: elasticsearch
---
# elasticsearch-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: myspace
  labels:
    service: elasticsearch
spec:
  replicas: 3
  serviceName: es-headless
  selector:
    matchLabels:
      service: elasticsearch
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/running
                operator: NotIn
                values:
                - "false"
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - es-headless
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - chown -R 1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-the-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: increase-the-ulimit
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
#         - name: bootstrap.memory_lock
#           value: "true"
          - name: cluster.name
            value: elasticsearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "elasticsearch-0.es-headless.myspace.svc.cluster.local,elasticsearch-1.es-headless.myspace.svc.cluster.local,elasticsearch-2.es-headless.myspace.svc.cluster.local"
          - name: cluster.initial_master_nodes
            value: "elasticsearch-0.es-headless.myspace.svc.cluster.local,elasticsearch-1.es-headless.myspace.svc.cluster.local,elasticsearch-2.es-headless.myspace.svc.cluster.local"
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
