# <cmd> kubectl apply -f zookeeper-deploy.yaml
#
# zookeeper-storage.yaml
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: local-storage
#provisioner: rancher.io/local-path
#volumeBindingMode: WaitForFirstConsumer
#---
# zookeeper-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zk-headless
  namespace: myspace
  labels:
    app: zk-headless
spec:
  clusterIP: None # Setting the clusterIP field in a service spec to 'None' makes the service headless.
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: follower
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: leader
    port: 3888
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper
---
# zookeeper-deploy.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: myspace
  labels:
    app: zookeeper
spec:
  replicas: 2
  serviceName: zk-headless
  selector:
    matchLabels:
      app: zookeeper
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/running
                operator: NotIn
                values:
                - "false"
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - zk-headless
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        resources: {}
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
#         - name: ZOO_SERVER_ID
#           value: "1"
          - name: ZOO_TICK_TIME
            value: "2000"
          - name: ZOO_PORT_NUMBER
            value: "2181"
          - name: ZOO_SERVERS
            value: zookeeper-0.zk-headless.myspace.svc.cluster.local:2888:3888,zookeeper-1.zk-headless.myspace.svc.cluster.local:2888:3888
#           value: zookeeper-0:2888:3888::1,zookeeper-1:2888:3888::2
        volumeMounts:
        - name: data
          mountPath: /bitnami/zookeeper
