apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebserver
  namespace: default
  labels:
    k8s-app: mywebserver
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: mywebserver
  template:
    metadata:
      labels:
        k8s-app: mywebserver
    spec:
      containers:
      - name: mywebserver
        image: httpd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      restartPolicy: Always
      terminationGracePeriodSeconds: 30