# Create a temporary busybox workspace to use
#
# Deploy the Nginx pods <run> kubectl apply -f kubernetes/busybox.yaml
# Deploy the Nginx pods <run> kubectl run -i -t busybox --image=radial/busyboxplus:curl
# Deploy the Nginx pods <run> kubectl attach -i -t busybox -c busybox
# Deploy the Nginx pods <run> kubectl exec -i -t deploy/busybox -- sh
# Deploy the Nginx pods <run> kubectl exec -i -t deploy/busybox -- nslookup nginx-testlb
# Deploy the Nginx pods <run> kubectl exec -i -t deploy/busybox -- nslookup foobar-service
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: myspace
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: radial/busyboxplus:curl
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args:
        - while true; do
            echo -en '\nMY_POD_NAME      = $MY_POD_NAME';
            echo -en '\nMY_POD_IP        = $MY_POD_IP';
            echo -en '\nMY_POD_UID       = $MY_POD_UID';
            echo -en '\nMY_NODE_NAME     = $MY_NODE_NAME';
            echo -en '\nMY_NODE_IP       = $MY_NODE_IP';
            echo -en '\nMY_POD_NAMESPACE = $MY_POD_NAMESPACE';
            sleep 5;
          done;
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
