# This config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
#
# (run) kind create cluster --config kubernetes/kind-cluster.yaml
# (run) kind delete cluster
# (run) kubectl create namespace myspace
# (run) kubectl config set-context — current — namespace=myspace
#
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
# the three workers node config
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
networking:
  ipFamily: ipv4
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases. Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16" # configure the subnet used for pod IPs by setting
  serviceSubnet: "10.96.0.0/12" # configure the Kubernetes service subnet used for service IPs by setting
  kubeProxyMode: "ipvs" # Between "iptables" and "ipvs". By default "iptables" is used
