# This config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
#
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-cluster development --insecure-skip-tls-verify
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-cluster production --insecure-skip-tls-verify
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-cluster kind-kind
#
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-credentials kind-kind
#
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-context dev-context
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-context prod-context
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-context kind-kind
#
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml view
#
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1
  name: development
- cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1
  name: production
- cluster:
    server: https://127.0.0.1
  name: kind-kind
contexts:
- context:
    cluster: development
    namespace: development
    user: kind-kind
  name: dev-context
- context:
    cluster: production
    namespace: production
    user: kind-kind
  name: prod-context
- context:
    cluster: kind-kind
    namespace: default
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
  user: {}
