# This config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
#
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-cluster development
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-cluster production
# (run) kubectl config --kubeconfig=kubernetes/kube-config.yaml set-cluster kind-kind
#
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1
  name: development
- cluster:
    server: https://127.0.0.1
  name: kind-kind
- cluster:
    server: https://127.0.0.1
  name: production
contexts:
- context:
    cluster: development
    namespace: default
    user: kind-kind
  name: dev-context
- context:
    cluster: production
    namespace: default
    user: kind-kind
  name: prod-context
- context:
    cluster: kind-kind
    namespace: default
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
  user: {}
