# To test the MetalLB setup and configuration.
#
# Deploy the Nginx pods <run> kubectl apply -f kubernetes/nginx-testlb.yaml
# Get the IP of the Nginx service <run> kubectl get svc -o wide
# Access the application <run> http://[your_nginx_service_external_ip]
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-testlb
  namespace: myspace
  labels:
    app: nginx
    component: testlb
spec:
  selector:
    matchLabels:
      app: nginx
      component: testlb
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        component: testlb
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-testlb
  namespace: myspace
  labels:
    app: nginx
    component: testlb
spec:
  type: LoadBalancer
  selector:
    app: nginx
    component: testlb
  ports:
  - port: 80
    name: http